
###
POST http://localhost:9093/api/v1/authenticate
Content-Type: application/json

{
  "username": "superadmin",
  "password": "$123_superadmin"
}

> {%
    client.global.set("my_jwt", response.body.jwtToken);
%}



###

POST http://localhost:9093/api/v1/userProfile/registration
Content-Type: application/json

{
"name": "Ferdous",
"userName": "root2",
"password": "123456"
}
####


###

GET http://localhost:9093/api/v1/userProfile/getDetail
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
####

