
###
POST http://localhost:9093/api/v1/authenticate
Content-Type: application/json

{
  "username": "superadmin",
  "password": "$123_superadmin"
}

> {%
    client.global.set("my_jwt", response.body.jwtToken);
%}

###

GET http://localhost:9093/api/v1/secureResourceTest
Content-Type: application/json
Authorization: Bearer {{my_jwt}}
####


GET http://localhost:9093//api/v1/sampleRegistration?name=shaiful&username=shaiful&password=456
Content-Type: application/json
####

