
###
GET http://localhost:9093/api/v1/stop/getOne?id=10
Content-Type: application/json
Authorization: Bearer {{my_jwt}}

###
GET http://localhost:9093/api/v1/stop/getAll
Content-Type: application/json
Authorization: Bearer {{my_jwt}}


